include:
  - project: 'gnome/citemplates'
    file: 'flatpak/flatpak_ci_initiative.yml'

flatpak:
  except:
    - poeditor
  extends: '.flatpak'
  variables:
    BUNDLE: "video-trimmer-nightly.flatpak"
    MANIFEST_PATH: "build-aux/org.gnome.gitlab.YaLTeR.VideoTrimmer.Devel.json"
    FLATPAK_MODULE: "video-trimmer"
    APP_ID: "org.gnome.gitlab.YaLTeR.VideoTrimmer.Devel"
    RUNTIME_REPO: "https://nightly.gnome.org/gnome-nightly.flatpakrepo"

rustfmt:
  except:
    - poeditor
  image: "rust:slim"
  script:
    - rustup component add rustfmt
    - echo -e "" >> src/config.rs
    - rustc -Vv && cargo -Vv
    - cargo fmt --version
    - cargo fmt --all -- --color=always --check
