[package]
name = "video-trimmer"
version = "0.1.0"
edition = "2018"
license = "GPL-3.0-or-later"

[dependencies]
nom = "6.1.2"
futures-util = "0.3.13"
once_cell = "1.7.2"
mime_guess = "2.0.3"
futures-channel = "0.3.13"

[dependencies.gstreamer]
git = "https://gitlab.freedesktop.org/gstreamer/gstreamer-rs.git"
features = ["v1_10"]

[dependencies.gtk]
git = "https://github.com/gtk-rs/gtk-rs.git"
features = ["v3_24"]

[dependencies.gettext-rs]
version = "0.6.0"
features = ["gettext-system"]
