[package]
name = "video-trimmer"
version = "0.1.0"
edition = "2021"
license = "GPL-3.0-or-later"

[dependencies]
adw = { version = "0.7.0", package = "libadwaita", features = ["v1_6"] }
futures-channel = "0.3.30"
futures-util = "0.3.30"
gettext-rs = { version = "0.7.1", features = ["gettext-system"] }
glib = { version = "0.20.3", features = ["log", "log_macros"] }
gtk = { version = "0.9.1", package = "gtk4", features = ["v4_16"] }
json = "0.12.4"
log = "0.4.22"
mime_guess = "2.0.5"
nom = "7.1.3"
